function gpt2finetuningtrainingloss = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  GPT2FINETUNINGTRAININGLOSS = IMPORTFILE1(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  GPT2FINETUNINGTRAININGLOSS = IMPORTFILE1(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  gpt2finetuningtrainingloss = importfile1("C:\Users\Jasper\Dropbox\RUG - ME\DL - Deep Learning\Practical 2\results\matlab\csv files\gpt2_finetuning_training_loss.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Apr-2021 10:32:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Step", "TrainingLoss"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
gpt2finetuningtrainingloss = readtable(filename, opts);

end