function markovrandomoutput = importtxt(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  MARKOVRANDOMOUTPUT = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a cell array.
%
%  MARKOVRANDOMOUTPUT = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  markovrandomoutput = importfile1("C:\Users\Jasper\Dropbox\RUG - ME\DL - Deep Learning\Practical 2\results\MarkovModel\markov_random_output.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Apr-2021 21:41:29

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "";

% Specify column names and types
opts.VariableNames = "ThebeginningoftheendforFoxjustliketheDemocratsamptheDNCwantedsa";
opts.VariableTypes = "string";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "ThebeginningoftheendforFoxjustliketheDemocratsamptheDNCwantedsa", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "ThebeginningoftheendforFoxjustliketheDemocratsamptheDNCwantedsa", "EmptyFieldRule", "auto");

% Import the data
markovrandomoutput = readtable(filename, opts);

%% Convert to output type
markovrandomoutput = table2cell(markovrandomoutput);
numIdx = cellfun(@(x) ~isnan(str2double(x)), markovrandomoutput);
markovrandomoutput(numIdx) = cellfun(@(x) {str2double(x)}, markovrandomoutput(numIdx));
end